# Generated by Django 5.0 on 2023-12-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['-time_create'], name='myprogram_p_time_cr_0f507a_idx'),
        ),
    ]
