# Generated by Django 5.0 on 2023-12-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprogram', '0002_alter_program_options_program_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
