# Generated by Django 5.0 on 2023-12-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprogram', '0003_alter_program_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
