# Generated by Django 5.0 on 2023-12-24 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprogram', '0005_category_program_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myprogram.category'),
        ),
    ]
