# Generated by Django 5.0 on 2023-12-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprogram', '0008_husband_program_husband'),
    ]

    operations = [
        migrations.AddField(
            model_name='husband',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
