# Generated by Django 5.0 on 2024-01-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprogram', '0010_uploadfiles_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%y/%m/%d/', verbose_name='Фото'),
        ),
    ]
